Add missing KCMUtils dependency in mms plugin
Without this, build fails with

kget/transfer-plugins/mmsthreads/dlgmms.h:22:10: fatal error: KCModule: No such file or directory