Fix for compile error after latest update to libktorrent (r1120202). Needs an error() function, otherwise compile fails with:
transfer-plugins/bittorrent/bttransferhandler.cpp: In member function 'void BTTransferHandler::createScanDlg()':                                      
transfer-plugins/bittorrent/bttransferhandler.cpp:81: error: cannot allocate an object of abstract type 'kt::ScanDlg'                                 
transfer-plugins/bittorrent/scandlg.h:40: note:   because the following virtual functions are pure within 'kt::ScanDlg':                              
libktorrent/datachecker/datacheckerlistener.h:67: note:  virtual void bt::DataCheckerListener::error(const QString&)

Assuming that just reporting the error, as is done a few lines above,
is the right thing to do.

svn path=/trunk/KDE/kdenetwork/kget/; revision=1138807